"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var definitions_1 = require("./plasmLockdrop/definitions");
Object.defineProperty(exports, "plasmLockdrop", { enumerable: true, get: function () { return definitions_1.default; } });
var definitions_2 = require("./dappsStaking/definitions");
Object.defineProperty(exports, "dappsStaking", { enumerable: true, get: function () { return definitions_2.default; } });
var definitions_3 = require("./plasmRewards/definitions");
Object.defineProperty(exports, "plasmRewards", { enumerable: true, get: function () { return definitions_3.default; } });
var definitions_4 = require("./trading/definitions");
Object.defineProperty(exports, "trading", { enumerable: true, get: function () { return definitions_4.default; } });
var definitions_5 = require("./ovm/definitions");
Object.defineProperty(exports, "ovm", { enumerable: true, get: function () { return definitions_5.default; } });
var definitions_6 = require("./plasma/definitions");
Object.defineProperty(exports, "plasma", { enumerable: true, get: function () { return definitions_6.default; } });
